server:
  port: ${PORT:8762}
        
## Classic Eureka configuration
eureka:
  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME:localhost}
    
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
      

## Enable service discovery (with Eureka)
## lower-case-service-id is mandatory, otherwise is retrieved in upper case from Eureka
spring:
  main:
    web-application-type: reactive
  application:
    name: gateway    
  cloud:
    gateway:
      enabled: true
      route-definition-locator:
        enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          filters:
            - StripPrefix=1
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]': ## For all routes
            allowedOrigins: ${ALLOWED_ORIGINS:*} # With '*' we allow all origins. We can restrict by indicating domains or ip + port, e.g. http://localhost:3000 (where our front is, or a Vercel domain)
            allowedHeaders: "*" ## All headers allowed
            allowedMethods: "*"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    urls:
      - name: catalogue
        url: /catalogue/v3/api-docs
      - name: payments
        url: /payments/v3/api-docs
    urls-primary-name: catalogue

## We enable the Actuator API to be able to access <<host>>/actuator/gateway/routes
## We expose the routings that have been automatically detected (all)
## Depending on the ROUTE_TABLES_ENABLED environment variable (true by default)
management:
  endpoint:
    gateway:
      access: ${ROUTE_TABLES_ENABLED:read_only}
  endpoints:
    web:
      exposure:
        include:
        - '*'
